import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className="px-4 md:px-8">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* <div className="h-[1000px] bg-red-500"></div> */}
            {children}
          </ThemeProvider>
        </body>
    </html> 
  )
}
